/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


function WolfMVC_PageComponent_Agenda_Render() {
    var minStart = 9999999999999;
    var maxEnd = 0;
    var end = new Array();
    var start = new Array();
    for (var i in extdata.appointments) {

        var datesplit = extdata.appointments[i].date_start.split("-");
        var timesplit = extdata.appointments[i].time_start.split(":");
        start[i] = Date.UTC(Number(datesplit[0]), Number(datesplit[1]), Number(datesplit[2]), Number(timesplit[0]), Number(timesplit[1]), 0);
        if (start[i] < minStart)
        minStart = start[i];
        var datesplit = extdata.appointments[i].due_date.split("-");
        var timesplit = extdata.appointments[i].time_end.split(":");
        end[i] = Date.UTC(Number(datesplit[0]), Number(datesplit[1]), Number(datesplit[2]), Number(timesplit[0]), Number(timesplit[1]), 0);
        if (end[i] > maxEnd)
        maxEnd = end[i];
        console.log(start[i] + " -> " + end[i]);
    }
    console.log(minStart+" -> "+maxEnd);
    var interval = maxEnd-minStart;
    console.log(interval);
    
    
    
}





var extdata = {
    appointments: [
        {"id": "839",
            "subject": "GIMMILLARO - F.lli LONARDI S.r.l.",
            "date_start": "2013-09-03",
            "due_date": "2013-09-03",
            "time_start": "15:00:00",
            "time_end": "16:00:00",
            "location": "37060 Gazzo Veronese VR, Italia",
        },
        {"id": "840",
            "subject": "Prova",
            "date_start": "2013-09-22",
            "due_date": "2013-09-22",
            "time_start": "14:10:00",
            "time_end": "15:10:00",
            "location": "",
        },
        {"id": "841",
            "subject": "CASO - L'ABITO NEL LAVORO S.N.C",
            "date_start": "2013-09-04",
            "due_date": "2013-09-04",
            "time_start": "11:30",
            "time_end": "12:30",
            "location": "Via Nettunense, KM 4,700 00040 Castel Gandolfo, RM",
        },
        {"id": "842",
            "subject": "GIMMILLARO - Ferrari Alfro srl",
            "date_start": "2013-09-11",
            "due_date": "2013-09-11",
            "time_start": "09:30:00",
            "time_end": "10:30:00",
            "location": "Via Frescà, 40, 37060 Gazzo Veronese VR, Italia",
        },
        {"id": "843",
            "subject": "GIMMILLARO - FERCART  SRL",
            "date_start": "2013-09-04",
            "due_date": "2013-09-04",
            "time_start": "16:00",
            "time_end": "17:00",
            "location": "via del lavoro 1 montagnana (PD)",
        },
        {"id": "844",
            "subject": "CASO - GUARNIERI SRL",
            "date_start": "2013-09-04",
            "due_date": "2013-09-04",
            "time_start": "13:00",
            "time_end": "14:00",
            "location": "VIA CASCINA PERGOLA, SAN MARTINO IN STRADA (LO)",
        },
        {"id": "845",
            "subject": "PIERRO - ORAS SRL",
            "date_start": "2013-09-04",
            "due_date": "2013-09-04",
            "time_start": "13:00",
            "time_end": "14:00",
            "location": "via di campo 29 san cesareo RM",
        },
        {"id": "846",
            "subject": "PIERRO - MARMISTA IGS MARMI SRL ",
            "date_start": "2013-09-04",
            "due_date": "2013-09-04",
            "time_start": "14:00",
            "time_end": "15:00",
            "location": "via tav san cesareo (RM) ",
        },
        {"id": "847",
            "subject": "CASO - B.R. SRL",
            "date_start": "2013-09-04",
            "due_date": "2013-09-04",
            "time_start": "10:30",
            "time_end": "11:30",
            "location": "viale risorgimento 2 Somaglia (LO)",
        },
        {"id": "848",
            "subject": "CASO - LOSI & C SNC ",
            "date_start": "2013-09-05",
            "due_date": "2013-09-05",
            "time_start": "9:30",
            "time_end": "10:30",
            "location": "Strada Provinciale 27, 26842 Cornovecchio LO, Italia",
        },
        {"id": "849",
            "subject": "PIERRO - CENTRO GRASSI ARICCIA SRL",
            "date_start": "2013-09-06",
            "due_date": "2013-09-06",
            "time_start": "8:30",
            "time_end": "9:30",
            "location": "via moletta 57 ariccia (RM)",
        },
        {"id": "850",
            "subject": "PIERRO - CO.ME.EL. SRL ",
            "date_start": "2013-09-18",
            "due_date": "2013-09-18",
            "time_start": "14:00",
            "time_end": "15:00",
            "location": "via IV negroni 63 ariccia (RM)",
        },
        {"id": "851",
            "subject": "CASO - MARMI LODI SRL",
            "date_start": "2013-09-05",
            "due_date": "2013-09-05",
            "time_start": "7:20",
            "time_end": "8:20",
            "location": "STRADA VECCHIA ANTICA CREMONESE 20, SAN MARTINO IN STRADA (LO)",
        },
        {"id": "852",
            "subject": "CASO - BRAMBINI FABRIZIO ",
            "date_start": "2013-09-09",
            "due_date": "2013-09-09",
            "time_start": "8:30",
            "time_end": "9:30",
            "location": "Strada Provinciale 187, 26815 Massalengo LO, Italia",
        },
        {"id": "853",
            "subject": "CASO - C.M.BRUSCHI SRL",
            "date_start": "2013-09-05",
            "due_date": "2013-09-05",
            "time_start": "12:30",
            "time_end": "13:30",
            "location": "STRADA LODIGIANA 13 SOMAGLIA (LO)",
        },
        {"id": "854",
            "subject": "CASO - ITALMEC SRL",
            "date_start": "2013-09-11",
            "due_date": "2013-09-11",
            "time_start": "11:30",
            "time_end": "12:30",
            "location": "Via Pietro Nenni, 6, 20060 Bussero MI, Italia",
        },
        {"id": "855",
            "subject": "GIMMILLARO - SUBA ALIMENTARE S.r.l.",
            "date_start": "2013-09-10",
            "due_date": "2013-09-10",
            "time_start": "14:00",
            "time_end": "15:00",
            "location": "Via Umbria, 14, 35043 MONSELICE - Zona Industr. Artig. E Commerciale PD, Italia",
        },
        {"id": "856",
            "subject": "PIERRO - Tecno Selciati di Carpineti Oberdan - c. snc ",
            "date_start": "2013-09-06",
            "due_date": "2013-09-06",
            "time_start": "13:15",
            "time_end": "14:15",
            "location": "VIA COLLE NASONE 172  ALBANO LAZIALE (RM)  ",
        },
        {"id": "857",
            "subject": "CASO - AUTOFFICINA EUROCAR & C SNC",
            "date_start": "2013-09-05",
            "due_date": "2013-09-05",
            "time_start": "13:00",
            "time_end": "14:00",
            "location": "VIA ERNESTO GROPPI 12 CODOGNO/LO",
        },
        {"id": "858",
            "subject": "PIERRO - TEAM LAZIO SRL",
            "date_start": "2013-09-06",
            "due_date": "2013-09-06",
            "time_start": "7:30",
            "time_end": "8:30",
            "location": "VIA IV NEGRONI, 18 Z. IND. ARICCIA (RM) ",
        },
        {"id": "859",
            "subject": "GIMMILLARO - AUTOFFICINA ELETTRAUTO DEMA SNC",
            "date_start": "2013-09-05",
            "due_date": "2013-09-05",
            "time_start": "13:00",
            "time_end": "14:00",
            "location": "via tezze di cereda 37 cornedo vicentino (VI)",
        },
        {"id": "860",
            "subject": "GIMMILLARO - B.M. DI BATTILANA MAURIZIO E DANILO SNC",
            "date_start": "2013-09-05",
            "due_date": "2013-09-05",
            "time_start": "9:00",
            "time_end": "10:00",
            "location": "via tezze di cereda 29 cornedo vicentino",
        },
        {"id": "861",
            "subject": "PIERRO - MO.VER SRL ",
            "date_start": "2013-09-06",
            "due_date": "2013-09-06",
            "time_start": "12:30",
            "time_end": "13:30",
            "location": "VIA VI NEGRONI  N.75 ARICCIA",
        },
        {"id": "862",
            "subject": "GIMMILLARO - M.I.4 S.R.L",
            "date_start": "2013-09-05",
            "due_date": "2013-09-05",
            "time_start": "11:30",
            "time_end": "12:30",
            "location": "Via 4 Novembre, 30, 36050 Montorso Vicentino VI, Italia",
        },
        {"id": "863",
            "subject": "PIERRO - BECHERELLI FRANCOD.I.",
            "date_start": "2013-09-05",
            "due_date": "2013-09-05",
            "time_start": "7:15",
            "time_end": "8:15",
            "location": "VIA FATEBENEFRATELLI 7 GENZANO DI ROMA RM",
        },
        {"id": "864",
            "subject": "GIMMILLARO - MAVI COLORIFICIO S.n.c.",
            "date_start": "2013-09-10",
            "due_date": "2013-09-10",
            "time_start": "9:00",
            "time_end": "10:00",
            "location": "Via Piemonte, 14 - 35043 Monselice PD",
        },
        {"id": "865",
            "subject": "GIMMILLARO - MERCATONE DI MONSELICE S.r.l.",
            "date_start": "2013-09-10",
            "due_date": "2013-09-10",
            "time_start": "7:30",
            "time_end": "8:30",
            "location": "Via Orti, 7A, 35043 Monselice PD, Italia",
        },
        {"id": "866",
            "subject": "CASO - BERNARDI DOMENICO SAS",
            "date_start": "2013-09-10",
            "due_date": "2013-09-10",
            "time_start": "8:00",
            "time_end": "9:00",
            "location": "Via Giacomo Brodolini, 4/6, 20863 Concorezzo MB, Italia",
        },
        {"id": "867",
            "subject": "PIERRO - MC MOTORS (DI)",
            "date_start": "2013-09-06",
            "due_date": "2013-09-06",
            "time_start": "11:30",
            "time_end": "12:30",
            "location": "LOCALITA' CERRETO REGINA MARGHERITA NETTUNO (RM)",
        },
        {"id": "868",
            "subject": "PIERRO - 1000 GOMME SRL",
            "date_start": "2013-09-05",
            "due_date": "2013-09-05",
            "time_start": "9:30",
            "time_end": "10:30",
            "location": "VIA CAPRIOLI  2 ,NETTUNO (RM)",
        },
        {"id": "869",
            "subject": "CASO - ARTICA SNC",
            "date_start": "2013-09-10",
            "due_date": "2013-09-10",
            "time_start": "9:00",
            "time_end": "10:00",
            "location": "Via Siro Brodolini,  10/B, 20863 Concorezzo MB, Italia",
        },
        {"id": "870",
            "subject": "CASO - M.E.C. SRL",
            "date_start": "2013-09-06",
            "due_date": "2013-09-06",
            "time_start": "8:00",
            "time_end": "9:00",
            "location": "VIA PADRE MERONI, 22031 ALBAVILLA (CO)",
        },
        {"id": "871",
            "subject": "GIMMILLARO - ARCOLEGNAMI S.r.l.",
            "date_start": "2013-09-06",
            "due_date": "2013-09-06",
            "time_start": "12:00",
            "time_end": "13:00",
            "location": "Via Avv. Gianni Augsto Ruffo, 34 - 37040 Arcole VR, Italia",
        },
        {"id": "872",
            "subject": "PIERRO - N.C.M. TECNOLOGY SRL",
            "date_start": "2013-09-05",
            "due_date": "2013-09-05",
            "time_start": "12:30",
            "time_end": "13:30",
            "location": "VIA DEL TRIDENTE N.15 NETTUNO (RM)",
        },
        {"id": "873",
            "subject": "CASO - VITERIA SMEL SNC",
            "date_start": "2013-09-06",
            "due_date": "2013-09-06",
            "time_start": "9:00",
            "time_end": "10:00",
            "location": "via buerga 8 monguzzo (CO)",
        },
        {"id": "874",
            "subject": "CASO - MONDONICO SRL",
            "date_start": "2013-09-06",
            "due_date": "2013-09-06",
            "time_start": "12:00",
            "time_end": "13:00",
            "location": "Viale Matteotti 66, 20092 Cinisello Balsamo MI, Italia",
        },
        {"id": "875",
            "subject": "GIMMILLARO - PICCINATO SERGIO SRL",
            "date_start": "2013-09-06",
            "due_date": "2013-09-06",
            "time_start": "13:30",
            "time_end": "14:30",
            "location": "VIA DELL'ARTIGIANATO 6 SAN BONIFACIO (Vr)",
        },
        {"id": "876",
            "subject": "GIMMILLARO - MANIFATTURA SARTORI S.r.l.",
            "date_start": "2013-09-06",
            "due_date": "2013-09-06",
            "time_start": "9:30",
            "time_end": "10:30",
            "location": "Via Ecce Homo, 8 - 37054 Nogara VR",
        },
        {"id": "877",
            "subject": "CASO - NR RCNI SRL",
            "date_start": "2013-09-06",
            "due_date": "2013-09-06",
            "time_start": "13:00",
            "time_end": "14:00",
            "location": "Via e Vicolo Casignolo 24, 20092 Cinisello Balsamo MI, Italia ",
        }

    ],
    count: 1
};

